# Unity Build for Windows

name: Build for Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ① プロジェクトをチェックアウト
      - name: Checkout project
        uses: actions/checkout@v4

      # ② ビルドを実行
      - name: Build with game-ci
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 6000.0.41f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # ③ ビルド成果物をアップロード
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: build/StandaloneWindows64